name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          webRenderer: canvaskit
          baseHref: /MacOsDock/